import { CourseCatalog } from '@/lib/types';

export const COURSE_CATEGORIES = [
  'Frontend Development',
  'Backend Development',
  'Systems Design',
] as const;

export const COURSE_DIFFICULTIES = [
  'Beginner',
  'Intermediate',
  'Advanced',
  'Mastery',
] as const;

export const COURSE_CATEGORY_COLORS: Record<string, string> = {
  'Frontend Development': 'bg-blue-100 text-blue-800',
  'Backend Development': 'bg-emerald-100 text-emerald-800',
  'Systems Design': 'bg-amber-100 text-amber-800',
};

export const COURSE_DIFFICULTY_COLORS: Record<string, string> = {
  Beginner: 'bg-green-100 text-green-800',
  Intermediate: 'bg-yellow-100 text-yellow-800',
  Advanced: 'bg-red-100 text-red-800',
  Mastery: 'bg-slate-900 text-white',
};

export const CODING_COURSES: CourseCatalog[] = [
  {
    id: '1',
    slug: 'frontend-development-beginner',
    title: 'Frontend Development Beginner',
    description: 'Start with HTML, CSS, and basic JavaScript while building your first responsive pages.',
    category: 'Frontend Development',
    difficulty: 'Beginner',
    duration: 240,
    totalQuizzes: 4,
    totalLessons: 12,
    instructor: 'Deveda Frontend Team',
    prerequisites: [],
    tags: ['html', 'css', 'javascript', 'responsive-design'],
    thumbnail: '',
    createdAt: '2026-03-10',
  },
  {
    id: '2',
    slug: 'frontend-development-foundations',
    title: 'Frontend Development Foundations',
    description: 'Deepen your HTML, CSS, and JavaScript fundamentals through interface-focused builds.',
    category: 'Frontend Development',
    difficulty: 'Beginner',
    duration: 300,
    totalQuizzes: 5,
    totalLessons: 14,
    instructor: 'Deveda Frontend Team',
    prerequisites: ['frontend-development-beginner'],
    tags: ['html', 'css', 'javascript', 'dom'],
    thumbnail: '',
    createdAt: '2026-03-10',
  },
  {
    id: '3',
    slug: 'frontend-development-intermediate',
    title: 'Frontend Development Intermediate',
    description: 'Move into stronger JavaScript patterns and an introduction to React for component thinking.',
    category: 'Frontend Development',
    difficulty: 'Intermediate',
    duration: 360,
    totalQuizzes: 6,
    totalLessons: 16,
    instructor: 'Deveda Frontend Team',
    prerequisites: ['frontend-development-foundations'],
    tags: ['html', 'css', 'javascript', 'react'],
    thumbnail: '',
    createdAt: '2026-03-10',
  },
  {
    id: '4',
    slug: 'frontend-development-advanced',
    title: 'Frontend Development Advanced',
    description: 'Build production-ready apps with React, Next.js, Tailwind CSS, JavaScript, and TypeScript.',
    category: 'Frontend Development',
    difficulty: 'Advanced',
    duration: 480,
    totalQuizzes: 8,
    totalLessons: 20,
    instructor: 'Deveda Frontend Team',
    prerequisites: ['frontend-development-intermediate'],
    tags: ['react', 'nextjs', 'tailwind', 'javascript', 'typescript'],
    thumbnail: '',
    createdAt: '2026-03-10',
  },
  {
    id: '5',
    slug: 'frontend-development-mastery',
    title: 'Frontend Development Mastery',
    description: 'Operate like a frontend engineer with architecture, performance, accessibility, and delivery discipline.',
    category: 'Frontend Development',
    difficulty: 'Mastery',
    duration: 540,
    totalQuizzes: 10,
    totalLessons: 24,
    instructor: 'Deveda Frontend Team',
    prerequisites: ['frontend-development-advanced'],
    tags: ['frontend-engineering', 'performance', 'accessibility', 'architecture'],
    thumbnail: '',
    createdAt: '2026-03-10',
  },
  {
    id: '6',
    slug: 'backend-development-python-apis',
    title: 'Backend Development: Introduction to Python and APIs',
    description: 'Learn Python fundamentals and how HTTP APIs work before building your first backend service.',
    category: 'Backend Development',
    difficulty: 'Beginner',
    duration: 260,
    totalQuizzes: 4,
    totalLessons: 12,
    instructor: 'Deveda Backend Team',
    prerequisites: [],
    tags: ['python', 'http', 'rest', 'apis'],
    thumbnail: '',
    createdAt: '2026-03-10',
  },
  {
    id: '7',
    slug: 'backend-development-fastapi',
    title: 'Backend Development: FastAPI',
    description: 'Use FastAPI to build validated, documented, and testable APIs with Python.',
    category: 'Backend Development',
    difficulty: 'Intermediate',
    duration: 320,
    totalQuizzes: 5,
    totalLessons: 14,
    instructor: 'Deveda Backend Team',
    prerequisites: ['backend-development-python-apis'],
    tags: ['python', 'fastapi', 'pydantic', 'api-design'],
    thumbnail: '',
    createdAt: '2026-03-10',
  },
  {
    id: '8',
    slug: 'backend-development-intermediate',
    title: 'Backend Development Intermediate',
    description: 'Add authentication, persistence, background jobs, and stronger service structure.',
    category: 'Backend Development',
    difficulty: 'Intermediate',
    duration: 400,
    totalQuizzes: 6,
    totalLessons: 18,
    instructor: 'Deveda Backend Team',
    prerequisites: ['backend-development-fastapi'],
    tags: ['authentication', 'databases', 'testing', 'background-jobs'],
    thumbnail: '',
    createdAt: '2026-03-10',
  },
  {
    id: '9',
    slug: 'backend-development-advanced',
    title: 'Backend Development Advanced',
    description: 'Design scalable backend systems with security, observability, performance, and reliability in mind.',
    category: 'Backend Development',
    difficulty: 'Advanced',
    duration: 500,
    totalQuizzes: 8,
    totalLessons: 22,
    instructor: 'Deveda Backend Team',
    prerequisites: ['backend-development-intermediate'],
    tags: ['architecture', 'security', 'performance', 'observability'],
    thumbnail: '',
    createdAt: '2026-03-10',
  },
  {
    id: '10',
    slug: 'systems-design-essentials',
    title: 'Systems Design Essentials',
    description: 'Understand tradeoffs in designing reliable, scalable systems using queues, caches, databases, and APIs.',
    category: 'Systems Design',
    difficulty: 'Advanced',
    duration: 420,
    totalQuizzes: 6,
    totalLessons: 16,
    instructor: 'Deveda Architecture Team',
    prerequisites: ['backend-development-intermediate'],
    tags: ['systems-design', 'distributed-systems', 'scalability', 'architecture'],
    thumbnail: '',
    createdAt: '2026-03-10',
  },
];
